### ISSUE TITLE
dj-rest-auth needs upgrade

### ISSUE THREAD

**Issue by niall-byrne** [grocerypanic/grocerypanic-backend#102]
There is a warning in the underlying allauth library.
dj-rest-auth has patched it, but have not yet released.

Incorporate their changes, and then release.

https://github.com/iMerica/dj-rest-auth/issues/506

**Comment by gitexel** [comment]
This issue needs to be patched in a new version 4.0.1 ASAP to mitigate this security [issue](https://pyup.io/packages/pypi/django-allauth/changelog#:~:text=versions%20(3.5%2C%203.6).-,Security%20notice,-%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%0A%0A%2D%20Even%20when)

**Comment by niall-byrne** [comment]
Addressed by d81cd4e266099b7d3863f1102174694925d007b9
